# Generated by Django 4.1.2 on 2022-10-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterKeys',
            new_name='CharacterKey',
        ),
    ]
