# Generated by Django 4.1.2 on 2022-10-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0003_remove_characterkey_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chinesecharacter',
            name='keys_set',
        ),
        migrations.AddField(
            model_name='chinesecharacter',
            name='keys_set',
            field=models.ManyToManyField(to='search_words.characterkey'),
        ),
    ]
