# Generated by Django 4.1.2 on 2022-11-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0004_remove_chinesecharacter_keys_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesecharacter',
            name='keys_set',
            field=models.ManyToManyField(related_name='characters', to='search_words.characterkey'),
        ),
    ]
