# Generated by Django 4.1.2 on 2023-01-18 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0007_alter_chinesecharacter_keys_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_text', models.TextField(help_text='Приведи пример на китайском', max_length=500, verbose_name='Текст китайского примера')),
            ],
            options={
                'verbose_name': ('Пример на китайском',),
                'verbose_name_plural': 'Примеры на китайском',
            },
        ),
        migrations.AlterModelOptions(
            name='characterkey',
            options={'ordering': ['pinyin'], 'verbose_name': 'Ключ', 'verbose_name_plural': 'Ключи'},
        ),
        migrations.AlterModelOptions(
            name='chinesecharacter',
            options={'ordering': ['pinyin'], 'verbose_name': 'Иероглиф', 'verbose_name_plural': 'Иероглифы'},
        ),
        migrations.AlterModelOptions(
            name='russianword',
            options={'ordering': ['word'], 'verbose_name': 'русское слово', 'verbose_name_plural': 'русские слова'},
        ),
        migrations.RemoveField(
            model_name='chinesecharacter',
            name='characters_number',
        ),
        migrations.RemoveField(
            model_name='chinesecharacter',
            name='keys_set',
        ),
        migrations.RemoveField(
            model_name='chinesecharacter',
            name='lines_number',
        ),
        migrations.RemoveField(
            model_name='russianword',
            name='chinese_meaning',
        ),
        migrations.RemoveField(
            model_name='russianword',
            name='first_letter',
        ),
        migrations.RemoveField(
            model_name='russianword',
            name='letters_number',
        ),
        migrations.AddField(
            model_name='chinesecharacter',
            name='character_keys',
            field=models.ManyToManyField(blank=True, help_text='Укажи состав ключей иероглифа', related_name='characters', to='search_words.characterkey', verbose_name='Ключи'),
        ),
        migrations.AlterField(
            model_name='characterkey',
            name='key',
            field=models.CharField(help_text='Введи китайский ключ', max_length=10, unique=True, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='characterkey',
            name='pinyin',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='characterkey',
            name='russian_meaning',
        ),
        migrations.AlterField(
            model_name='chinesecharacter',
            name='character',
            field=models.CharField(help_text='Введи слово на китайском', max_length=20, verbose_name='Китайское слово'),
        ),
        migrations.AlterField(
            model_name='chinesecharacter',
            name='pinyin',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='chinesecharacter',
            name='russian_meaning',
        ),
        migrations.RemoveField(
            model_name='chinesecharacter',
            name='usage_examples',
        ),
        migrations.AlterField(
            model_name='russianword',
            name='word',
            field=models.CharField(help_text='Введи русское слово', max_length=50, unique=True, verbose_name='Слово'),
        ),
        migrations.CreateModel(
            name='RussianExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_text', models.TextField(help_text='Приведи пример на русском', max_length=500, verbose_name='Текст русского примера')),
                ('chinese_translation', models.ForeignKey(help_text='Дай перевод на китайском', on_delete=django.db.models.deletion.CASCADE, related_name='russian_translations', to='search_words.chineseexample', verbose_name='Перевод на китайском')),
            ],
            options={
                'verbose_name': ('Пример на русском',),
                'verbose_name_plural': 'Примеры на русском',
                'ordering': ['russian_text'],
            },
        ),
        migrations.AddField(
            model_name='chineseexample',
            name='russian_translation',
            field=models.ForeignKey(help_text='Дай перевод на русском', on_delete=django.db.models.deletion.CASCADE, related_name='chinese_translations', to='search_words.russianexample', verbose_name='Перевод на русском'),
        ),
        migrations.AddField(
            model_name='russianword',
            name='usage_examples',
            field=models.ManyToManyField(blank=True, help_text='Примеры употребления на русском', related_name='russian_words', to='search_words.chineseexample', verbose_name='Примеры употребления'),
        ),
        migrations.AddField(
            model_name='characterkey',
            name='russian_meaning',
            field=models.ManyToManyField(blank=True, related_name='character_keys', to='search_words.russianword', verbose_name='Русское значение'),
        ),
        migrations.AddField(
            model_name='chinesecharacter',
            name='russian_meaning',
            field=models.ManyToManyField(blank=True, help_text='Дай русский перевод слова', related_name='characters', to='search_words.russianword', verbose_name='Русское значение'),
        ),
        migrations.AddField(
            model_name='chinesecharacter',
            name='usage_examples',
            field=models.ManyToManyField(blank=True, help_text='Приведи примеры с этим иероглифом', related_name='characters', to='search_words.russianexample', verbose_name='Примеры употребления иероглифа'),
        ),
    ]
