# Generated by Django 4.1.2 on 2023-01-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0009_alter_characterkey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseexample',
            name='russian_translation',
            field=models.ForeignKey(default='Пусто', help_text='Дай перевод на русском', on_delete=django.db.models.deletion.CASCADE, related_name='chinese_translations', to='search_words.russianexample', verbose_name='Перевод на русском'),
        ),
    ]
