# Generated by Django 4.1.2 on 2023-01-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0011_remove_chineseexample_russian_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseexample',
            name='chinese_text',
            field=models.TextField(default='Пусто', help_text='Приведи пример на китайском', max_length=500, verbose_name='Текст китайского примера'),
        ),
    ]
