# Generated by Django 4.1.2 on 2023-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0012_alter_chineseexample_chinese_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterkey',
            name='russian_meaning',
            field=models.ManyToManyField(blank=True, help_text='Напиши русский первод', related_name='character_keys', to='search_words.russianword', verbose_name='Русское значение'),
        ),
        migrations.AlterField(
            model_name='chinesecharacter',
            name='usage_examples',
            field=models.ManyToManyField(blank=True, help_text='Приведи примеры с этим иероглифом', related_name='characters', to='search_words.chineseexample', verbose_name='Примеры употребления иероглифа'),
        ),
        migrations.AlterField(
            model_name='russianword',
            name='usage_examples',
            field=models.ManyToManyField(blank=True, help_text='Примеры употребления на русском', related_name='russian_words', to='search_words.russianexample', verbose_name='Примеры употребления'),
        ),
    ]
