# Generated by Django 4.1.2 on 2023-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0013_alter_characterkey_russian_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinesecharacter',
            name='part_of_speech',
            field=models.CharField(choices=[('ГЛ.', 'глагол'), ('СУЩ.', 'существительное'), ('ПРИЛ.', 'прилагательное'), ('МЕСТ.', 'местоимение'), ('НАР.', 'наречие'), ('ПРИЧ.', 'причастие'), ('ДЕЕПРИЧ.', 'деепричастие')], default='Пусто', max_length=20),
        ),
        migrations.AddField(
            model_name='russianword',
            name='part_of_speech',
            field=models.CharField(choices=[('ГЛ.', 'глагол'), ('СУЩ.', 'существительное'), ('ПРИЛ.', 'прилагательное'), ('МЕСТ.', 'местоимение'), ('НАР.', 'наречие'), ('ПРИЧ.', 'причастие'), ('ДЕЕПРИЧ.', 'деепричастие')], default='Пусто', max_length=20),
        ),
    ]
