# Generated by Django 4.1.2 on 2023-01-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0014_chinesecharacter_part_of_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesecharacter',
            name='usage_examples',
            field=models.ManyToManyField(blank=True, help_text='Приведи примеры с этим иероглифом', related_name='characters', to='search_words.examplepair', verbose_name='Примеры употребления иероглифа'),
        ),
        migrations.AlterField(
            model_name='examplepair',
            name='chinese_example',
            field=models.ForeignKey(default='Пусто', help_text='Дай перевод на китайском', on_delete=django.db.models.deletion.CASCADE, related_name='example_pairs', to='search_words.chineseexample', verbose_name='Перевод на китайском'),
        ),
        migrations.AlterField(
            model_name='examplepair',
            name='russian_example',
            field=models.ForeignKey(default='Пусто', help_text='Дай перевод на русском', on_delete=django.db.models.deletion.CASCADE, related_name='example_pairs', to='search_words.russianexample', verbose_name='Перевод на русском'),
        ),
    ]
