# Generated by Django 4.1.2 on 2023-02-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_words', '0016_englishexample_alter_russianword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplepair',
            name='english_example',
            field=models.ForeignKey(blank=True, default=1, help_text='Дай перевод на английском', on_delete=django.db.models.deletion.CASCADE, related_name='example_pairs', to='search_words.englishexample', verbose_name='Перевод на английском'),
        ),
    ]
